<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Trevor Harrington">

<title>Pollution Project - DBH</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="Pollution_Project_Part_1_files/libs/clipboard/clipboard.min.js"></script>
<script src="Pollution_Project_Part_1_files/libs/quarto-html/quarto.js"></script>
<script src="Pollution_Project_Part_1_files/libs/quarto-html/popper.min.js"></script>
<script src="Pollution_Project_Part_1_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Pollution_Project_Part_1_files/libs/quarto-html/anchor.min.js"></script>
<link href="Pollution_Project_Part_1_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Pollution_Project_Part_1_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Pollution_Project_Part_1_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Pollution_Project_Part_1_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Pollution_Project_Part_1_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

<script src="Pollution_Project_Part_1_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="Pollution_Project_Part_1_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pollution Project - DBH</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Trevor Harrington </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="snhu-arboretum-stream-pollution-project" class="level1">
<h1>SNHU Arboretum Stream Pollution Project</h1>
<div class="cell">

</div>
<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<hr>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>The objective of this study was to choose two five by five meter plots in the SNHU arboretum as representatives of tree size close to a water source, versus further away. For this first part of this study, the measurements taken in these plots are used to determine biomass, which can be leveraged to calculate carbon and CO2 sequestration using a given conversion factor. For the second part of this study, tree density calculated in these two plots will be used to try and estimate the amount of trees present, and by extension the amount of CO2 sequestered by the SNHU Arboretum.</p>
<p>This study collected measurements of diameter at breast height (DBH) for five trees within each of the plots. Because trees grow at fairly consistent rates (depending on the species), DBH is an essential metric in both forestry and environmental research for understanding a number of factors about a forest. On top of those being calculated in this study, DBH can be important for understanding tree age and health, wildlife habitat assessments, and forest management / inventory surveys.</p>
<p>Biomass is the mass of living organisms in a given area, and provides a crucial measurement for understanding ecological health and carbon sequestration in a forest or ecosystem. In this study, biomass is study in situ and only provides a estimated value; less accuracy, but at no cost to the trees or ecosystem <span class="citation" data-cites="vorster2020">Vorster et al. (<a href="#ref-vorster2020" role="doc-biblioref">2020</a>)</span>. One of the most important characteristics</p>
<hr>
</section>
<section id="materials-and-methods" class="level2">
<h2 class="anchored" data-anchor-id="materials-and-methods">Materials and Methods</h2>
<p>On March 20th, 2023, measurements were taken at the SNHU Arboretum in the vicinity of a stream pollution experiment scheduled for the remainder of the semester. In this study, biomass is calculated using the allometric scaling equation with the diameter at breast height (DBH) in centimeters. measurements were recorded directly into a word document using and iPad pro. Quality of the observations was accounted for by using multiple people to verify measurements. Plots were chosen for this experiment due to proximity to a water source, as well as elevation to see if any impact to DBH can be identified at a factor of access to water.</p>
<p>The initial step involved collecting DBH data for two sets of trees within 15 x 15-foot plots. This information will be beneficial when examining further details about the stream. The “near water” trees were measured within a range of 1 to 5 yards surrounding a seasonal second-order stream as it flows through a tunnel beneath a pathway. Located approximately 100 feet from the parking lot, this plot experiences significant foot traffic. The “distant from water” plot was situated roughly 75 feet from the initial point, away from pedestrian areas. Trees within a 15 square feet cluster were measured at breast height using a tape measure.</p>
<p>The following code was created to analyze the DBH data. Both datasets are initially converted into a data frame in R Studio. Ideally, the original Excel file should be linked, but since the data set only comprises 10 variables, manually entering the DBH values into R is the most straightforward approach. The code’s annotations provide detailed explanations of the calculations, eliminating the need for a separate methods description.</p>
<hr>
<section id="i---calculating-biomass-carbon-co2-sequestration-for-each-plots" class="level3">
<h3 class="anchored" data-anchor-id="i---calculating-biomass-carbon-co2-sequestration-for-each-plots">I - Calculating Biomass, Carbon &amp; CO2 Sequestration for Each Plots</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate variables for each set of vectors</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>dbh_near_water <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">48.2</span>, <span class="fl">32.3</span>, <span class="fl">40.6</span>, <span class="fl">21.0</span>, <span class="fl">44.7</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>dbh_distant_from_water <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">54.5</span>, <span class="fl">70.2</span>, <span class="fl">29.0</span>, <span class="fl">26.2</span>, <span class="fl">46.7</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert DBH from inches to centimeters</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">#dbh_near_water &lt;- dbh_near_water * 2.54</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">#dbh_distant_from_water &lt;- dbh_distant_from_water * 2.54</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshape datasets into dataframes and merge into a dataframe</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>df_near_water <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">DBH =</span> dbh_near_water, <span class="at">Location =</span> <span class="st">"Near Water"</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>df_distant_from_water <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">DBH =</span> dbh_distant_from_water, <span class="at">Location =</span> <span class="st">"Distant from Water"</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>combined_df <span class="ot">&lt;-</span> <span class="fu">rbind</span>(df_near_water, df_distant_from_water)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a column to the dataframe for biomass</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="do">## Biomass is calculated using the allometric equation provided in class</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>combined_df<span class="sc">$</span><span class="st">"Biomass (kg/tree)"</span> <span class="ot">&lt;-</span> (<span class="fl">41.173</span> <span class="sc">*</span> combined_df<span class="sc">$</span>DBH <span class="sc">-</span> <span class="fl">409.5</span>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a column for Carbon (kg/tree) </span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="do">## Carbon is found by multiplying biomass by the % mass that is carbon. This value (45%) provides a general estimate for carbon, useful for in situ studies. </span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>combined_df<span class="sc">$</span><span class="st">"Carbon (kg/tree)"</span> <span class="ot">&lt;-</span> combined_df<span class="sc">$</span>Biomass <span class="sc">*</span> <span class="fl">0.45</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a column for CO2 (kg/tree)</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="do">## CO2 is found by multiplying Carbon by the difference between the molar masses. This is done to determine the amount of potential atmospheric carbon that could be generated if the tree was used for combustion. </span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>combined_df<span class="sc">$</span><span class="st">"CO2_per_tree (kg/tree)"</span> <span class="ot">&lt;-</span> (combined_df<span class="sc">$</span>Carbon <span class="sc">*</span> <span class="fl">3.66666666667</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="listing-results" class="level4">
<h4 class="anchored" data-anchor-id="listing-results">Listing results</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>combined_df <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate_if</span>(is.numeric, comma) <span class="sc">%&gt;%</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="st">"striped"</span>, <span class="st">"hover"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> DBH </th>
   <th style="text-align:left;"> Location </th>
   <th style="text-align:left;"> Biomass (kg/tree) </th>
   <th style="text-align:left;"> Carbon (kg/tree) </th>
   <th style="text-align:left;"> CO2_per_tree (kg/tree) </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 48.2 </td>
   <td style="text-align:left;"> Near Water </td>
   <td style="text-align:left;"> 1,575 </td>
   <td style="text-align:left;"> 709 </td>
   <td style="text-align:left;"> 2,599 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 32.3 </td>
   <td style="text-align:left;"> Near Water </td>
   <td style="text-align:left;"> 920 </td>
   <td style="text-align:left;"> 414 </td>
   <td style="text-align:left;"> 1,519 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 40.6 </td>
   <td style="text-align:left;"> Near Water </td>
   <td style="text-align:left;"> 1,262 </td>
   <td style="text-align:left;"> 568 </td>
   <td style="text-align:left;"> 2,083 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 21.0 </td>
   <td style="text-align:left;"> Near Water </td>
   <td style="text-align:left;"> 455 </td>
   <td style="text-align:left;"> 205 </td>
   <td style="text-align:left;"> 751 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 44.7 </td>
   <td style="text-align:left;"> Near Water </td>
   <td style="text-align:left;"> 1,431 </td>
   <td style="text-align:left;"> 644 </td>
   <td style="text-align:left;"> 2,361 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 54.5 </td>
   <td style="text-align:left;"> Distant from Water </td>
   <td style="text-align:left;"> 1,834 </td>
   <td style="text-align:left;"> 825 </td>
   <td style="text-align:left;"> 3,027 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 70.2 </td>
   <td style="text-align:left;"> Distant from Water </td>
   <td style="text-align:left;"> 2,481 </td>
   <td style="text-align:left;"> 1,116 </td>
   <td style="text-align:left;"> 4,093 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 29.0 </td>
   <td style="text-align:left;"> Distant from Water </td>
   <td style="text-align:left;"> 785 </td>
   <td style="text-align:left;"> 353 </td>
   <td style="text-align:left;"> 1,294 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 26.2 </td>
   <td style="text-align:left;"> Distant from Water </td>
   <td style="text-align:left;"> 669 </td>
   <td style="text-align:left;"> 301 </td>
   <td style="text-align:left;"> 1,104 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 46.7 </td>
   <td style="text-align:left;"> Distant from Water </td>
   <td style="text-align:left;"> 1,513 </td>
   <td style="text-align:left;"> 681 </td>
   <td style="text-align:left;"> 2,497 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<hr>
</section>
</section>
<section id="ii---calculating-averages-for-each-plot" class="level3">
<h3 class="anchored" data-anchor-id="ii---calculating-averages-for-each-plot">II - Calculating Averages for Each Plot</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>combined_df <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Location) <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise</span>(<span class="st">"Average Biomass (kg/tree)"</span> <span class="ot">=</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Biomass (kg/tree)</span><span class="st">`</span>),</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>           <span class="st">"Average Carbon (kg/tree)"</span> <span class="ot">=</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Carbon (kg/tree)</span><span class="st">`</span>),</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>           <span class="st">"Average CO2 (kg/tree)"</span> <span class="ot">=</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">CO2_per_tree (kg/tree)</span><span class="st">`</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>           )<span class="sc">%&gt;%</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="st">"striped"</span>, <span class="st">"hover"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Location </th>
   <th style="text-align:right;"> Average Biomass (kg/tree) </th>
   <th style="text-align:right;"> Average Carbon (kg/tree) </th>
   <th style="text-align:right;"> Average CO2 (kg/tree) </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Distant from Water </td>
   <td style="text-align:right;"> 1456.5 </td>
   <td style="text-align:right;"> 655.4 </td>
   <td style="text-align:right;"> 2403.2 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Near Water </td>
   <td style="text-align:right;"> 1128.7 </td>
   <td style="text-align:right;"> 507.9 </td>
   <td style="text-align:right;"> 1862.4 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<section id="graphing-results" class="level4">
<h4 class="anchored" data-anchor-id="graphing-results">Graphing Results</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the data</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(combined_df) <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(Location,DBH)) <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(Location,DBH)) <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"DBH Comparison: Near Water vs Distant from Water"</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Location"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Diameter at Breast Height (DBH, cm)"</span>) <span class="sc">+</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Pollution_Project_Part_1_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="running-t-test-for-to-compare-dbh-between-the-plots" class="level3">
<h3 class="anchored" data-anchor-id="running-t-test-for-to-compare-dbh-between-the-plots">Running t-test for to compare DBH between the plots</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(dbh_distant_from_water,dbh_near_water)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  dbh_distant_from_water and dbh_near_water
t = 0.83622, df = 6.524, p-value = 0.4326
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -14.88615  30.80615
sample estimates:
mean of x mean of y 
    45.32     37.36 </code></pre>
</div>
</div>
<hr>
</section>
<section id="iii---extrapolating-the-results-for-the-arboretum" class="level3">
<h3 class="anchored" data-anchor-id="iii---extrapolating-the-results-for-the-arboretum">III - Extrapolating the Results for the Arboretum</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>  combined_df <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>     <span class="st">"Total CO2 in Plot (kg/tree)"</span> <span class="ot">=</span> <span class="fl">2132.8</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>     <span class="st">"Plot Size (m^2)"</span> <span class="ot">=</span> <span class="st">"6.5"</span>,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>     <span class="st">"Tree Density (trees/m^2)"</span> <span class="ot">=</span> <span class="st">"1.5"</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>     <span class="st">"Arboretum Area (m^2)"</span> <span class="ot">=</span> <span class="dv">97124</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>     <span class="st">"# in Arboretum Trees"</span> <span class="ot">=</span> <span class="fl">97124.6</span> <span class="sc">*</span> <span class="fl">1.5</span>,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>     <span class="st">"CO2 in Arboretum (kg)"</span> <span class="ot">=</span> <span class="fl">145686.9</span> <span class="sc">*</span> <span class="fl">2132.8</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(is.numeric, comma) <span class="sc">%&gt;%</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="st">"striped"</span>, <span class="st">"hover"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Total CO2 in Plot (kg/tree) </th>
   <th style="text-align:left;"> Plot Size (m^2) </th>
   <th style="text-align:left;"> Tree Density (trees/m^2) </th>
   <th style="text-align:left;"> Arboretum Area (m^2) </th>
   <th style="text-align:left;"> # in Arboretum Trees </th>
   <th style="text-align:left;"> CO2 in Arboretum (kg) </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 2,133 </td>
   <td style="text-align:left;"> 6.5 </td>
   <td style="text-align:left;"> 1.5 </td>
   <td style="text-align:left;"> 97,124 </td>
   <td style="text-align:left;"> 145,687 </td>
   <td style="text-align:left;"> 310,721,020 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<hr>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<p>Based on the t-test results for these two groups (t = 0.83622, df = 6.524, p-value = 0.4326), there is no significant difference between the mean DBH of trees near water ( mean = 37.36 cm) and distant from water ( mean = 45.32 cm) at the 95% confidence level. The confidence interval for the difference in means ranges from -14.89 to 30.81, which includes zero, further indicating that the true difference in means might be insignificant.</p>
<p>It is likely the small sample size has an impact of the results of this experiment and expanding the amount of trees observed in each group may provide a more clear deviation between the two groups. Another metric that would likely greatly improve accuracy is a height, which can be used to generate a more accurate estimation for biomass. Overall, this project is a relatively low-confidence example of a CO2 calculation, but accurately describes the process by which this is done.</p>
<p>The results of this this study were used in part III to attempt to estimate the total carbon sequestration present in the biomass in the SNHU arboretum. These results were estimated based of a 24 square mile estimate found <span class="citation" data-cites="Arbnet">(<a href="#ref-Arbnet" role="doc-biblioref"><strong>Arbnet?</strong></a>)</span></p>
<p>Considering the graph, this does seem to support a statistically significant difference between the measurements taken near and far from the stream. Distant from the water, there seems to be a significant amount of deviation from the mean that could account for a much less significant difference between these two groups.</p>

</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-vorster2020" class="csl-entry" role="doc-biblioentry">
Vorster, Anthony G., Paul H. Evangelista, Atticus E. L. Stovall, and Seth Ex. 2020. <span>“Variability and Uncertainty in Forest Biomass Estimates from the Tree to Landscape Scale: The Role of Allometric Equations.”</span> <em>Carbon Balance and Management</em> 15 (1). <a href="https://doi.org/10.1186/s13021-020-00143-6">https://doi.org/10.1186/s13021-020-00143-6</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>