<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Trevor Harrington">

<title>T-Test in RStudio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="T_Test_in_RStudio_files/libs/clipboard/clipboard.min.js"></script>
<script src="T_Test_in_RStudio_files/libs/quarto-html/quarto.js"></script>
<script src="T_Test_in_RStudio_files/libs/quarto-html/popper.min.js"></script>
<script src="T_Test_in_RStudio_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="T_Test_in_RStudio_files/libs/quarto-html/anchor.min.js"></script>
<link href="T_Test_in_RStudio_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="T_Test_in_RStudio_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="T_Test_in_RStudio_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="T_Test_in_RStudio_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="T_Test_in_RStudio_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

<script src="T_Test_in_RStudio_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="T_Test_in_RStudio_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">T-Test in RStudio</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Trevor Harrington </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="t-tests-in-rstudio-loblolly-vs.-pine-trees" class="level1">
<h1>T-Tests in RStudio: Loblolly vs.&nbsp;Pine Trees</h1>
<div class="cell">

</div>
<section id="t-testing-when-and-why-to-use-t-tests" class="level2">
<h2 class="anchored" data-anchor-id="t-testing-when-and-why-to-use-t-tests">T-Testing: When and Why to Use T-Tests</h2>
<section id="what-is-a-t-test" class="level3">
<h3 class="anchored" data-anchor-id="what-is-a-t-test">What is a t-test</h3>
<ul>
<li><p>A t-test is a statistical test used to determine if there is a significant difference between the means of two groups. For example, let’s say you wanted to know if there is a significant difference in the average mass between Loblolly pine and White pine trees. You could use a t-test to compare the mean mass of a group of Loblolly trees to the mean mass of a group of White Pine.</p></li>
<li><p>The t-test generates a t-value, which is a measure of the difference between the means of the two groups relative to the variability within each group. The t-value is then compared to a critical value from a t-distribution table, based on the degrees of freedom (which is determined by the sample size of each group).</p>
<ul>
<li>If the calculated t-value is greater than the critical value from the table, then we can conclude that there is a significant difference between the means of the two groups. In other words, the difference between the two groups is unlikely to be due to chance.</li>
</ul></li>
<li><p>there are different types of t-tests, depending on the nature of the data and the research question. The two most common types are the independent samples t-test, which compares the means of two independent groups, and the paired samples t-test, which compares the means of two related groups (e.g.&nbsp;pre-test and post-test scores for the same individuals).</p></li>
</ul>
</section>
<section id="short-summary-of-the-math" class="level3">
<h3 class="anchored" data-anchor-id="short-summary-of-the-math">Short Summary of the Math</h3>
<ul>
<li><p>First, you need to <strong>calculate the sample means and sample standard deviations for each group</strong>. Let’s call the sample means “x-bar 1” and “x-bar 2” and the sample standard deviations “s1” and “s2.”</p></li>
<li><p>Next, you calculate the <strong>standard error of the difference between the means</strong>, which is the standard deviation of the sampling distribution of the difference between the means. This can be calculated using the formula:</p>
<ul>
<li><p><strong>SE = sqrt(s1^2/n1 + s2^2/n2)</strong></p></li>
<li><p>“n1” and “n2” are the sample sizes for each group.</p></li>
</ul></li>
<li><p>Then, you <strong>calculate the t-value</strong> using the formula:</p>
<ul>
<li><strong>t = (x-bar 1 - x-bar 2) / SE</strong></li>
</ul></li>
</ul>
<p>This t-value represents the difference between the means of the two groups in terms of standard errors.</p>
<ul>
<li><p>Finally, you compare the calculated t-value to a critical value from a t-distribution table, based on the <strong>degrees of freedom (df)</strong>. The degrees of freedom for an independent samples t-test are calculated as:</p>
<ul>
<li><p><strong>df = n1 + n2 - 2</strong></p></li>
<li><p>“n1” is the sample size of the first group, “n2” is the sample size of the second group, and 2 represents the number of sample means being estimated.</p></li>
</ul></li>
</ul>
<p>If the calculated t-value is greater than the critical value from the table, then you can reject the null hypothesis and conclude that there is a significant difference between the means of the two groups. If the calculated t-value is not greater than the critical value, then you fail to reject the null hypothesis and conclude that there is not enough evidence to support a significant difference between the means of the two groups.</p>
<ul>
<li><p>The <strong>critical value</strong> in a t-test represents the value that divides the distribution of t-values into two regions: the region of t-values that are unlikely to occur by chance (i.e., the rejection region) and the region of t-values that are likely to occur by chance (i.e., the non-rejection region).</p></li>
<li><p>The critical value is determined by the degrees of freedom (df), which is based on the sample sizes of the two groups being compared. <strong>The larger the sample sizes, the larger the degrees of freedom and the smaller the critical value</strong>. Conversely, the smaller the sample sizes, the smaller the degrees of freedom and the larger the critical value.</p>
<ul>
<li>Critical value is calculated based off of degrees if freedom via a <strong>distribution table</strong></li>
</ul></li>
</ul>
<hr>
</section>
</section>
<section id="viewing-the-data" class="level2">
<h2 class="anchored" data-anchor-id="viewing-the-data">Viewing the data</h2>
<ul>
<li>always start with viewing a table what the data contains and generating an exploratory graph to show the correlation you hope to predict</li>
</ul>
<section id="creating-a-table" class="level3">
<h3 class="anchored" data-anchor-id="creating-a-table">Creating a Table</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>datum <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"C:/School/23SPDAY/FieldMethodsandTech/Practice Data/linear regression/t-testing/Class Activity 8.csv"</span>,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(datum) <span class="sc">%&gt;%</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">4</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="st">"striped"</span>, <span class="st">"hover"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Tree </th>
   <th style="text-align:right;"> Mass </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Loblolly pine </td>
   <td style="text-align:right;"> 88.5256 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Loblolly pine </td>
   <td style="text-align:right;"> 109.6834 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Loblolly pine </td>
   <td style="text-align:right;"> 102.9445 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Loblolly pine </td>
   <td style="text-align:right;"> 111.3871 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Loblolly pine </td>
   <td style="text-align:right;"> 113.4311 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Loblolly pine </td>
   <td style="text-align:right;"> 79.7784 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</section>
<section id="generating-a-graph" class="level3">
<h3 class="anchored" data-anchor-id="generating-a-graph">Generating a Graph</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate standard deviation for each tree type</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>sd_values <span class="ot">&lt;-</span> <span class="fu">tapply</span>(datum<span class="sc">$</span>Mass, datum<span class="sc">$</span>Tree, sd)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Mass<span class="sc">~</span><span class="fu">as.factor</span>(Tree), <span class="at">data=</span>datum,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Tree Mass by Tree Type"</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Tree Type"</span>,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Mass (kg)"</span> )</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">legend =</span> <span class="fu">paste</span>(<span class="fu">unique</span>(datum<span class="sc">$</span>Tree), </span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">" (SD= "</span>, <span class="fu">round</span>(sd_values, <span class="dv">2</span>), <span class="st">")"</span>, <span class="at">sep =</span> <span class="st">""</span>), </span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">1</span>, <span class="at">col =</span> <span class="fu">seq_along</span>(<span class="fu">unique</span>(datum<span class="sc">$</span>Tree)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Test_in_RStudio_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
</section>
</section>
<section id="running-a-t-test" class="level2">
<h2 class="anchored" data-anchor-id="running-a-t-test">Running a t-test</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>results<span class="ot">=</span><span class="fu">t.test</span>(Mass<span class="sc">~</span>Tree,<span class="at">data=</span>datum,<span class="at">var.equal=</span><span class="cn">FALSE</span>) <span class="do">### run a t-test, call results 'results'</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co">#default is var.equal=FALSE which is standard for t-tests; allows for unequal variance of groups</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>results <span class="do">### prints results - Note absence of 'summary' statement - one of few tests that doesn't use 'summary'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Mass by Tree
t = 5.9739, df = 26.182, p-value = 2.561e-06
alternative hypothesis: true difference in means between group Loblolly pine and group White pine is not equal to 0
95 percent confidence interval:
 14.35215 29.40224
sample estimates:
mean in group Loblolly pine    mean in group White pine 
                  103.54574                    81.66855 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Note results don't provide estimate of effect!</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout-note div callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Conclusion Statement
</div>
</div>
<div class="callout-body-container callout-body" style="border: 1px solid #ccc;   background-color: #f2f2f2;   color: #333;   padding: 10px;   margin: 10px 0;">
<p>The independent samples t-test indicates strong evidence that the average mass of trees in the Loblolly pine group is significantly different from the average mass of trees in the White pine group, at 103.55 kg and 81.67 kg respectively (t = 5.9739, df = 26.182, p = 2.561x10^-3)</p>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>